// @generated by protoc-gen-connect-es v1.6.0 with parameter "target=ts,import_extension=none"
// @generated from file kannon/mailer/apiv1/mailerapiv1.proto (package pkg.kannon.mailer.apiv1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { SendHTMLReq, SendRes, SendTemplateReq } from "./mailerapiv1_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service pkg.kannon.mailer.apiv1.Mailer
 */
export const Mailer = {
  typeName: "pkg.kannon.mailer.apiv1.Mailer",
  methods: {
    /**
     * @generated from rpc pkg.kannon.mailer.apiv1.Mailer.SendHTML
     */
    sendHTML: {
      name: "SendHTML",
      I: SendHTMLReq,
      O: SendRes,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc pkg.kannon.mailer.apiv1.Mailer.SendTemplate
     */
    sendTemplate: {
      name: "SendTemplate",
      I: SendTemplateReq,
      O: SendRes,
      kind: MethodKind.Unary,
    },
  }
} as const;

