// @generated by protoc-gen-es v2.13.0 with parameter "target=ts,import_extension=.js"
// @generated from file kannon/mailer/types/email.proto (package pkg.kannon.mailer.types, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kannon/mailer/types/email.proto.
 */
export const file_kannon_mailer_types_email: GenFile = /*@__PURE__*/
  fileDesc("Ch9rYW5ub24vbWFpbGVyL3R5cGVzL2VtYWlsLnByb3RvEhdwa2cua2Fubm9uLm1haWxlci50eXBlcyJyCgtFbWFpbFRvU2VuZBIQCghlbWFpbF9pZBgBIAEoCRIMCgRmcm9tGAIgASgJEgoKAnRvGAMgASgJEhMKC3JldHVybl9wYXRoGAQgASgJEgwKBGJvZHkYBSABKAwSFAoMc2hvdWxkX3JldHJ5GAYgASgIQjpaOGdpdGh1Yi5jb20va2Fubm9uLWVtYWlsL2thbm5vbi9wcm90by9rYW5ub24vbWFpbGVyL3R5cGVzYgZwcm90bzM");

/**
 * @generated from message pkg.kannon.mailer.types.EmailToSend
 */
export type EmailToSend = Message<"pkg.kannon.mailer.types.EmailToSend"> & {
  /**
   * @generated from field: string email_id = 1;
   */
  emailId: string;

  /**
   * @generated from field: string from = 2;
   */
  from: string;

  /**
   * @generated from field: string to = 3;
   */
  to: string;

  /**
   * @generated from field: string return_path = 4;
   */
  returnPath: string;

  /**
   * @generated from field: bytes body = 5;
   */
  body: Uint8Array;

  /**
   * @generated from field: bool should_retry = 6;
   */
  shouldRetry: boolean;
};

/**
 * Describes the message pkg.kannon.mailer.types.EmailToSend.
 * Use `create(EmailToSendSchema)` to create a new message.
 */
export const EmailToSendSchema: GenMessage<EmailToSend> = /*@__PURE__*/
  messageDesc(file_kannon_mailer_types_email, 0);

