// @generated by protoc-gen-es v2.13.0 with parameter "target=ts,import_extension=.js"
// @generated from file kannon/mailer/types/send.proto (package pkg.kannon.mailer.types, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { TrackingPolicy } from "../../tracking/types/tracking_pb.js";
import { file_kannon_tracking_types_tracking } from "../../tracking/types/tracking_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kannon/mailer/types/send.proto.
 */
export const file_kannon_mailer_types_send: GenFile = /*@__PURE__*/
  fileDesc("Ch5rYW5ub24vbWFpbGVyL3R5cGVzL3NlbmQucHJvdG8SF3BrZy5rYW5ub24ubWFpbGVyLnR5cGVzIiYKBlNlbmRlchINCgVlbWFpbBgBIAEoCRINCgVhbGlhcxgCIAEoCSLYAQoJUmVjaXBpZW50Eg0KBWVtYWlsGAEgASgJEj4KBmZpZWxkcxgCIAMoCzIuLnBrZy5rYW5ub24ubWFpbGVyLnR5cGVzLlJlY2lwaWVudC5GaWVsZHNFbnRyeRJACgh0cmFja2luZxgDIAEoCzIpLnBrZy5rYW5ub24udHJhY2tpbmcudHlwZXMuVHJhY2tpbmdQb2xpY3lIAIgBARotCgtGaWVsZHNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBQgsKCV90cmFja2luZyIhCgdIZWFkZXJzEgoKAnRvGAEgAygJEgoKAmNjGAIgAygJIisKE09uZUNsaWNrVW5zdWJzY3JpYmUSFAoMdXJsX3RlbXBsYXRlGAEgASgJQjpaOGdpdGh1Yi5jb20va2Fubm9uLWVtYWlsL2thbm5vbi9wcm90by9rYW5ub24vbWFpbGVyL3R5cGVzYgZwcm90bzM", [file_kannon_tracking_types_tracking]);

/**
 * @generated from message pkg.kannon.mailer.types.Sender
 */
export type Sender = Message<"pkg.kannon.mailer.types.Sender"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string alias = 2;
   */
  alias: string;
};

/**
 * Describes the message pkg.kannon.mailer.types.Sender.
 * Use `create(SenderSchema)` to create a new message.
 */
export const SenderSchema: GenMessage<Sender> = /*@__PURE__*/
  messageDesc(file_kannon_mailer_types_send, 0);

/**
 * @generated from message pkg.kannon.mailer.types.Recipient
 */
export type Recipient = Message<"pkg.kannon.mailer.types.Recipient"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: map<string, string> fields = 2;
   */
  fields: { [key: string]: string };

  /**
   * The Recipient-level Tracking Policy — the most specific level of the
   * cascade, where a caller states the consent it holds in its own CRM
   * (ADR 0002). States nothing when omitted, which imposes no restriction of
   * its own and leaves the Batch and Domain levels to decide.
   *
   * Consent may only narrow: an `off` here wins over a Domain-level `full`,
   * but a `full` here does not win over a Domain-level `off`. A Recipient
   * stating a Mode above its Domain's ceiling is Rejected on its own, with a
   * reason in SendRes.rejected_recipients, while the rest of the Batch
   * proceeds — one bad row does not fail a send of thousands.
   *
   * @generated from field: optional pkg.kannon.tracking.types.TrackingPolicy tracking = 3;
   */
  tracking?: TrackingPolicy | undefined;
};

/**
 * Describes the message pkg.kannon.mailer.types.Recipient.
 * Use `create(RecipientSchema)` to create a new message.
 */
export const RecipientSchema: GenMessage<Recipient> = /*@__PURE__*/
  messageDesc(file_kannon_mailer_types_send, 1);

/**
 * @generated from message pkg.kannon.mailer.types.Headers
 */
export type Headers = Message<"pkg.kannon.mailer.types.Headers"> & {
  /**
   * @generated from field: repeated string to = 1;
   */
  to: string[];

  /**
   * @generated from field: repeated string cc = 2;
   */
  cc: string[];
};

/**
 * Describes the message pkg.kannon.mailer.types.Headers.
 * Use `create(HeadersSchema)` to create a new message.
 */
export const HeadersSchema: GenMessage<Headers> = /*@__PURE__*/
  messageDesc(file_kannon_mailer_types_send, 2);

/**
 * OneClickUnsubscribe is the sender's own unsubscribe endpoint, carried in the
 * List-Unsubscribe and List-Unsubscribe-Post headers (RFC 8058).
 *
 * Kannon personalises, emits and DKIM-signs it, and does nothing else with it:
 * it never calls the endpoint, keeps no suppression list, and records no
 * engagement when a recipient uses it. The URL travels in a header, so it is
 * never rewritten for click tracking.
 *
 * Stated per Batch. There is no Domain-level default and no Recipient-level
 * override — an unsubscribe on a password reset offers something the sender
 * cannot honour, and personalising the template is already what makes the
 * endpoint per-Recipient.
 *
 * @generated from message pkg.kannon.mailer.types.OneClickUnsubscribe
 */
export type OneClickUnsubscribe = Message<"pkg.kannon.mailer.types.OneClickUnsubscribe"> & {
  /**
   * The https URL of the endpoint, as a template.
   *
   * The endpoint MUST accept POST with body `List-Unsubscribe=One-Click` and
   * unsubscribe the recipient with no further confirmation. Supplying a URL
   * here asserts that: Kannon cannot verify it, and a message advertising
   * one-click that does not honour it is worse than one that never advertised
   * it, since the recipient believes they have unsubscribed.
   *
   * `{{ field }}` placeholders are substituted per Delivery from the
   * Recipient's fields, plus `email`, which Kannon supplies as the Recipient's
   * address unless the caller passes a field of that name itself. Substituted
   * values are percent-encoded, so pass raw values rather than pre-encoded
   * ones.
   *
   * A template that is unparseable or not https fails the whole call. A
   * Recipient whose fields leave a placeholder unresolved is Rejected on its
   * own, with reason `unsubscribe_url_unresolved`.
   *
   * @generated from field: string url_template = 1;
   */
  urlTemplate: string;
};

/**
 * Describes the message pkg.kannon.mailer.types.OneClickUnsubscribe.
 * Use `create(OneClickUnsubscribeSchema)` to create a new message.
 */
export const OneClickUnsubscribeSchema: GenMessage<OneClickUnsubscribe> = /*@__PURE__*/
  messageDesc(file_kannon_mailer_types_send, 3);

