// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=.js"
// @generated from file kannon/mailer/types/send.proto (package pkg.kannon.mailer.types, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kannon/mailer/types/send.proto.
 */
export const file_kannon_mailer_types_send: GenFile = /*@__PURE__*/
  fileDesc("Ch5rYW5ub24vbWFpbGVyL3R5cGVzL3NlbmQucHJvdG8SF3BrZy5rYW5ub24ubWFpbGVyLnR5cGVzIiYKBlNlbmRlchINCgVlbWFpbBgBIAEoCRINCgVhbGlhcxgCIAEoCSKJAQoJUmVjaXBpZW50Eg0KBWVtYWlsGAEgASgJEj4KBmZpZWxkcxgCIAMoCzIuLnBrZy5rYW5ub24ubWFpbGVyLnR5cGVzLlJlY2lwaWVudC5GaWVsZHNFbnRyeRotCgtGaWVsZHNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBIiEKB0hlYWRlcnMSCgoCdG8YASADKAkSCgoCY2MYAiADKAlCOlo4Z2l0aHViLmNvbS9rYW5ub24tZW1haWwva2Fubm9uL3Byb3RvL2thbm5vbi9tYWlsZXIvdHlwZXNiBnByb3RvMw");

/**
 * @generated from message pkg.kannon.mailer.types.Sender
 */
export type Sender = Message<"pkg.kannon.mailer.types.Sender"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string alias = 2;
   */
  alias: string;
};

/**
 * Describes the message pkg.kannon.mailer.types.Sender.
 * Use `create(SenderSchema)` to create a new message.
 */
export const SenderSchema: GenMessage<Sender> = /*@__PURE__*/
  messageDesc(file_kannon_mailer_types_send, 0);

/**
 * @generated from message pkg.kannon.mailer.types.Recipient
 */
export type Recipient = Message<"pkg.kannon.mailer.types.Recipient"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: map<string, string> fields = 2;
   */
  fields: { [key: string]: string };
};

/**
 * Describes the message pkg.kannon.mailer.types.Recipient.
 * Use `create(RecipientSchema)` to create a new message.
 */
export const RecipientSchema: GenMessage<Recipient> = /*@__PURE__*/
  messageDesc(file_kannon_mailer_types_send, 1);

/**
 * @generated from message pkg.kannon.mailer.types.Headers
 */
export type Headers = Message<"pkg.kannon.mailer.types.Headers"> & {
  /**
   * @generated from field: repeated string to = 1;
   */
  to: string[];

  /**
   * @generated from field: repeated string cc = 2;
   */
  cc: string[];
};

/**
 * Describes the message pkg.kannon.mailer.types.Headers.
 * Use `create(HeadersSchema)` to create a new message.
 */
export const HeadersSchema: GenMessage<Headers> = /*@__PURE__*/
  messageDesc(file_kannon_mailer_types_send, 2);

