// @generated by protoc-gen-es v2.13.0 with parameter "target=ts,import_extension=.js"
// @generated from file kannon/tracking/types/tracking.proto (package pkg.kannon.tracking.types, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file kannon/tracking/types/tracking.proto.
 */
export const file_kannon_tracking_types_tracking: GenFile = /*@__PURE__*/
  fileDesc("CiRrYW5ub24vdHJhY2tpbmcvdHlwZXMvdHJhY2tpbmcucHJvdG8SGXBrZy5rYW5ub24udHJhY2tpbmcudHlwZXMigAEKDlRyYWNraW5nUG9saWN5EjYKBW9wZW5zGAEgASgOMicucGtnLmthbm5vbi50cmFja2luZy50eXBlcy5UcmFja2luZ01vZGUSNgoFbGlua3MYAiABKA4yJy5wa2cua2Fubm9uLnRyYWNraW5nLnR5cGVzLlRyYWNraW5nTW9kZSq3AQoMVHJhY2tpbmdNb2RlEh0KGVRSQUNLSU5HX01PREVfVU5TUEVDSUZJRUQQABIVChFUUkFDS0lOR19NT0RFX09GRhABEhsKF1RSQUNLSU5HX01PREVfQU5PTllNT1VTEAISHgoaVFJBQ0tJTkdfTU9ERV9QU0VVRE9OWU1PVVMQAxIcChhUUkFDS0lOR19NT0RFX0lERU5USUZJRUQQBBIWChJUUkFDS0lOR19NT0RFX0ZVTEwQBUI8WjpnaXRodWIuY29tL2thbm5vbi1lbWFpbC9rYW5ub24vcHJvdG8va2Fubm9uL3RyYWNraW5nL3R5cGVzYgZwcm90bzM");

/**
 * TrackingPolicy is a pair of TrackingModes, one governing opens and one
 * governing links. Stated at domain, batch and recipient level, where a lower
 * level may only restrict what the level above allows.
 *
 * @generated from message pkg.kannon.tracking.types.TrackingPolicy
 */
export type TrackingPolicy = Message<"pkg.kannon.tracking.types.TrackingPolicy"> & {
  /**
   * @generated from field: pkg.kannon.tracking.types.TrackingMode opens = 1;
   */
  opens: TrackingMode;

  /**
   * @generated from field: pkg.kannon.tracking.types.TrackingMode links = 2;
   */
  links: TrackingMode;
};

/**
 * Describes the message pkg.kannon.tracking.types.TrackingPolicy.
 * Use `create(TrackingPolicySchema)` to create a new message.
 */
export const TrackingPolicySchema: GenMessage<TrackingPolicy> = /*@__PURE__*/
  messageDesc(file_kannon_tracking_types_tracking, 0);

/**
 * TrackingMode is how much one engagement channel may be observed. The scale is
 * ordered by increasing collection, but the rank order lives in Go rather than
 * in these numbers, so a Mode can be inserted mid-scale without renumbering the
 * wire.
 *
 * @generated from enum pkg.kannon.tracking.types.TrackingMode
 */
export enum TrackingMode {
  /**
   * States nothing, and so imposes no restriction of its own.
   *
   * @generated from enum value: TRACKING_MODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The channel is not observed at all.
   *
   * @generated from enum value: TRACKING_MODE_OFF = 1;
   */
  OFF = 1,

  /**
   * Counted in aggregate only; nothing retained that isolates one recipient.
   *
   * @generated from enum value: TRACKING_MODE_ANONYMOUS = 2;
   */
  ANONYMOUS = 2,

  /**
   * Linkable within a single batch, carrying no recipient identity.
   * Reserved: selecting it is rejected as unsupported.
   *
   * @generated from enum value: TRACKING_MODE_PSEUDONYMOUS = 3;
   */
  PSEUDONYMOUS = 3,

  /**
   * Attributed to the recipient.
   *
   * @generated from enum value: TRACKING_MODE_IDENTIFIED = 4;
   */
  IDENTIFIED = 4,

  /**
   * Attributed, plus the IP address and user agent of the request.
   *
   * @generated from enum value: TRACKING_MODE_FULL = 5;
   */
  FULL = 5,
}

/**
 * Describes the enum pkg.kannon.tracking.types.TrackingMode.
 */
export const TrackingModeSchema: GenEnum<TrackingMode> = /*@__PURE__*/
  enumDesc(file_kannon_tracking_types_tracking, 0);

